dockercoins: webui: fix library/image mismatch
The latest reddis which is `npm install`ed, is not compatable with
`node:4-slim`.

The error looks like:
```
dockercoins_webui_1
/node_modules/redis/dist/index.js:26
       ...options
       ^^^

SyntaxError: Unexpected token
```

Since we're installing the latest stable libraries, it probably makes
sense to use the `lts-slim` image.

Note the WORKDIR needs to be set after node 15.

Signed-off-by: David Scott <dave.scott@docker.com>